# Generated by Django 5.2 on 2025-07-25 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_type', models.CharField(choices=[('online', 'Online Reporting'), ('physical', 'Physical Reporting')], default='online', max_length=10)),
                ('reporting_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_application.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_application.student')),
            ],
            options={
                'ordering': ['-reporting_date'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
