# Generated by Django 5.2 on 2025-07-25 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0004_alter_room_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_position', models.CharField(choices=[('bed_1', 'Bed 1'), ('bed_2', 'Bed 2'), ('bed_3', 'Bed 3'), ('bed_4', 'Bed 4')], max_length=10)),
                ('bed_number', models.CharField(help_text='Unique bed identifier', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('maintenance_status', models.CharField(choices=[('good', 'Good Condition'), ('needs_repair', 'Needs Repair'), ('under_maintenance', 'Under Maintenance'), ('out_of_order', 'Out of Order')], default='good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_beds', to='core_application.academicyear')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='core_application.room')),
            ],
            options={
                'ordering': ['room', 'bed_position'],
                'unique_together': {('room', 'academic_year', 'bed_position')},
            },
        ),
    ]
