# Generated by Django 5.2 on 2025-07-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0006_hostelbooking_hostelincident_hostelpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomAllocation',
        ),
    ]
